name: TEST
on:
  workflow_dispatch:
  
jobs: 
  Reponame:
    runs-on: ubuntu-latest
    steps:
      - run: |
         GITHUB_WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA/checks?check_suite_id=$GITHUB_CHECK_SUITE_ID"
         echo  ${{ github.workflow }} ParentJobName
         echo  ${{ github.run_number }} ParentJobId
         echo $GITHUB_WORKFLOW_URL
         
        
