name: STALE_NOTIFICATION_pattern_test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload test.csv as artifact
        uses: actions/upload-artifact@v3
        with:
          name: StaleBranchList.csv
          path: ${{ github.workspace }}/test.csv
