name: DLT_pattern_test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs: 
  Get_Stale_Branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          
          sed -i "s/,/ /g" test.txt
          
          echo --------test.txt---------------
          cat ${{ github.workspace }}/test.txt
          
          awk 'BEGIN{ FS= "|"; OFS=","; print "Branch,Last Committer Name,Committer Date"}; NR > 0{print $1, $2, $3;}' ${{ github.workspace }}/test.txt > ${{ github.workspace }}/test.csv
          
          echo -----------test.csv------
          cat ${{ github.workspace }}/test.csv
          
          file="${{ github.workspace }}/.github/days.txt"
          Number_of_days=`grep Number_of_days $file |cut -d= -f2`
          Headsup_duration=`grep Headsup_duration $file |cut -d= -f2`
          echo ===================
          echo $Number_of_days
          echo $Headsup_duration is the headsup duration
         
          days=$(( $Number_of_days + $Headsup_duration ))
                  
          echo ------------days with headsup duration-----------------
          echo $days
          
          date_Xdays_before_TodayYear=$(date --date="$days days ago" +"%Y")
          date_Xdays_before_TodayMonth=$(date --date="$days days ago" +"%m")
          date_Xdays_before_TodayDay=$(date --date="$days days ago" +"%d")
          
          date_Xdays_before_Today="$date_Xdays_before_TodayYear-$date_Xdays_before_TodayMonth-$date_Xdays_before_TodayDay"
          
          echo ----------------date_Xdays_before_Today_headsup_duration_also_added-----------
          echo $date_Xdays_before_Today
          
          echo --------showing dates less than "$date_Xdays_before_Today"------------
          awk -v date_Xdays_before_Today="$date_Xdays_before_Today" '$NF < date_Xdays_before_Today' ${{ github.workspace }}/test.csv  >> ${{ github.workspace }}/Stale.csv
          
          
          echo ---------Stale.csv---
          cat ${{ github.workspace }}/Stale.csv
          echo --------------------------------
      
      - name: Upload Stale.csv as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Stale
          path: ${{ github.workspace }}/Stale.csv   
    
  Delete_Stale_Branches:
    runs-on: ubuntu-latest
    needs: [Get_Stale_Branches]
    environment: STALE
    steps:
     - uses: actions/checkout@v2

     - uses: actions/download-artifact@v3
       with:
         name:  Stale
         path: ${{ github.workspace }}/StaleBranches 
     
     - run: |
         ls -lrta  
         cd StaleBranches/
         ls -lrta
         cat Stale.csv
         cd ..
         pwd
         
     - name: Deleting stale branch  
       run: |
           pwd
           ls -lrta
           
           echo -----------StaleBranchname.csv-----------------
           sed -i '1d' ${{ github.workspace }}/StaleBranches/Stale.csv | cut -d ',' -f 1 ${{ github.workspace }}/StaleBranches/Stale.csv > ${{ github.workspace }}/StaleBranchnameTest.csv
           cat ${{ github.workspace }}/StaleBranchnameTest.csv
           echo -----------------------------------------------
           
    
