name: STALE_NOTIFICATION
on:
  workflow_dispatch:
  
jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch details file
        run:  |
          REPO_NAME=${{ github.event.repository.name }}
          echo $REPO_NAME
          git clone https://github.com/2115-27/$REPO_NAME.git
          cd $REPO_NAME/
          
          git branch -a --sort=-committerdate  --format='%(refname:short) |%(authorname)| %(committerdate:short)'>> ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~origin/~~g" ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~,~~g" ${{ github.workspace }}/BranchDetails.txt
          
          echo -----------BranchDetails.txt---------------
          cat ${{ github.workspace }}/BranchDetails.txt
     
      - name: Send notification
        run: |
          sudo apt-get install mailutils
          TO_ADDRESS="malavika.manoj@infosys.com"
          FROM_ADDRESS="athulyams2000@gmail.com"
          SUBJECT="Mail Server Hosting Demo"
          BODY="This is a linux mail system. Linux is one of the email operating systems which can be used to send and receive emails."

          echo ${BODY}| mail -s ${SUBJECT} ${TO_ADDRESS} -- -r ${FROM_ADDRESS}
