name: STALE_NOTIFICATION
on:
  workflow_dispatch:

jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch details file
        run:  |
          ls -lrta
          REPO_NAME=${{ github.event.repository.name }}
          git clone https://github.com/2115-27/$REPO_NAME.git
          cd $REPO_NAME/
          
          git branch -a --sort=-committerdate  --format='%(refname:short) |%(authorname)| %(committerdate:short)'| sed /\${{ github.ref_name }}/d>> ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~origin/~~g" ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~,~~g" ${{ github.workspace }}/BranchDetails.txt
          
          echo -----------BranchDetails.txt---------------
          cat ${{ github.workspace }}/BranchDetails.txt
          
          awk 'BEGIN{ FS= "|"; OFS=","; print "Branch,Last Committer Name,Committer Date"}; NR > 0{print $1, $2, $3;}' ${{ github.workspace }}/BranchDetails.txt > ${{ github.workspace }}/BranchList.csv
          
          echo --------BranchList.csv---------------
          cat ${{ github.workspace }}/BranchList.csv
          
          file="${{ github.workspace }}/.github/days.txt"
          Number_of_days=`grep Number_of_days $file |cut -d= -f2`
          Headsup_duration=`grep Headsup_duration $file |cut -d= -f2`
          
          echo ===================
          echo $Number_of_days
         
         
          days=$Number_of_days
                  
          echo ------------days-----------------
          echo $days
          
          date_Xdays_before_TodayYear=$(date --date="$days days ago" +"%Y")
          date_Xdays_before_TodayMonth=$(date --date="$days days ago" +"%m")
          date_Xdays_before_TodayDay=$(date --date="$days days ago" +"%d")
          
          date_Xdays_before_Today="$date_Xdays_before_TodayYear-$date_Xdays_before_TodayMonth-$date_Xdays_before_TodayDay"
          
          echo ----------------date_Xdays_before_Today_headsup_duration_not_added-----------
          echo $date_Xdays_before_Today
          
          File=${{ github.workspace }}/.github/StalebranchExclusion.json
              Official_Branch_List=($(jq -r '.Branches' $File))
              for i in "${Official_Branch_List[@]}"
              do            
                  echo -------------------------------
                  echo $i
              done
              
          
          echo -------------------testing-------------------------
          awk -v Branches="$Branches" -v HF_Branch="$HF_Branch" -v RL_Branch="$RL_Branch " -v MSTR_Branch="$MSTR_Branch" '!($0 ~ ("^" Branches) || $0 ~ ("^" HF_Branch) || $0 ~ ("^" RL_Branch) || $0 ~ ("^" MSTR_Branch))' ${{ github.workspace }}/BranchList.csv

          
#           echo --------showing dates less than "$date_Xdays_before_Today"------------
#           awk -v date_Xdays_before_Today="$date_Xdays_before_Today" '$NF < date_Xdays_before_Today' ${{ github.workspace }}/BranchList2.csv  >> ${{ github.workspace }}/StaleBranchList.csv
          
#           echo ---------StaleBranchList.csv---
#           cat ${{ github.workspace }}/StaleBranchList.csv
      
#       - name: Upload StaleBranchList.csv as artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: StaleBranchList.csv
#           path: ${{ github.workspace }}/StaleBranchList.csv
     
#       - name : Sending notification
#         run: |
#           echo sending notification
          
     
