name: STALE_NOTIFICATION
on:
  workflow_dispatch:

jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch details file
        run:  |
            
            #!/bin/bash

            # Create an array of fruits
            fruits=("apple" "banana" "cherry" "date" "elderberry")

            # Get the number of elements in the array
            num_elements=${#fruits[@]}

            # Loop through the array and assign each element to a variable
            for (( i=0; i<$num_elements; i++ )); do
            # Create a variable name using the current index
            var_name="fruit_$i"
            # Assign the current element to the variable
            eval "$var_name=${fruits[i]}"
            done

            # Print out each variable to confirm they were set correctly
            for (( i=0; i<$num_elements; i++ )); do
            var_name="fruit_$i"
            echo "${!var_name}"
            done
