name: STALE_NOTIFICATION
on:
  workflow_dispatch:

jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch details file
        run:  |
          ls -lrta
          REPO_NAME=${{ github.event.repository.name }}
          git clone https://github.com/2115-27/$REPO_NAME.git
          cd $REPO_NAME/
          
          git branch -a --sort=-committerdate  --format='%(refname:short) |%(authorname)| %(committerdate:short)'| sed /\${{ github.ref_name }}/d>> ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~origin/~~g" ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~,~~g" ${{ github.workspace }}/BranchDetails.txt
          
          echo -----------BranchDetails.txt---------------
          cat ${{ github.workspace }}/BranchDetails.txt
          
          awk 'BEGIN{ FS= "|"; OFS=","; print "Branch,Last Committer Name,Committer Date"}; NR > 0{print $1, $2, $3;}' ${{ github.workspace }}/BranchDetails.txt > ${{ github.workspace }}/BranchList.csv
          
          echo --------BranchList.csv---------------
          cat ${{ github.workspace }}/BranchList.csv
          
          file="${{ github.workspace }}/.github/days.txt"
          Number_of_days=`grep Number_of_days $file |cut -d= -f2`
          Headsup_duration=`grep Headsup_duration $file |cut -d= -f2`
          
          echo ===================
          echo $Number_of_days
         
         
          days=$Number_of_days
                  
          echo ------------days-----------------
          echo $days
          
          date_Xdays_before_TodayYear=$(date --date="$days days ago" +"%Y")
          date_Xdays_before_TodayMonth=$(date --date="$days days ago" +"%m")
          date_Xdays_before_TodayDay=$(date --date="$days days ago" +"%d")
          
          date_Xdays_before_Today="$date_Xdays_before_TodayYear-$date_Xdays_before_TodayMonth-$date_Xdays_before_TodayDay"
          
          echo ----------------date_Xdays_before_Today_headsup_duration_not_added-----------
          echo $date_Xdays_before_Today
          
          Dev_Branch=$(cat .github/StalebranchExclusion.json | jq -r '.DEVELOPMENT_BRANCH')
          HF_Branch=$(cat .github/StalebranchExclusion.json | jq -r '.HOTFIX_BRANCH')
          RL_Branch=$(cat .github/StalebranchExclusion.json | jq -r '.RELEASE_BRANCH')
          MSTR_Branch=$(cat .github/StalebranchExclusion.json | jq -r '.MASTER_BRANCH')
          
          echo "---------------Branches te exclude----------------"
          echo $Dev_Branch
          echo $HF_Branch
          echo ${RL_Branch}is the release branch
          echo $MSTR_Branch
          
          echo -------------------testing-------------------------
          awk -v Dev_Branch='$Dev_Branch' -v HF_Branch="$HF_Branch" -v RL_Branch="$RL_Branch" -v MSTR_Branch="$MSTR_Branch" '!/^(Dev_Branch|HF_Branch|ag-authjs-canary-6 |MSTR_Branch)/' ${{ github.workspace }}/BranchList.csv 
          awk -v Dev_Branch="$Dev_Branch" -v HF_Branch="$HF_Branch" -v RL_Branch="$RL_Branch" -v MSTR_Branch="$MSTR_Branch" '!($0 ~ ("^" Dev_Branch) || $0 ~ ("^" HF_Branch))' input.txt

          
#           echo --------showing dates less than "$date_Xdays_before_Today"------------
#           awk -v date_Xdays_before_Today="$date_Xdays_before_Today" '$NF < date_Xdays_before_Today' ${{ github.workspace }}/BranchList2.csv  >> ${{ github.workspace }}/StaleBranchList.csv
          
#           echo ---------StaleBranchList.csv---
#           cat ${{ github.workspace }}/StaleBranchList.csv
      
#       - name: Upload StaleBranchList.csv as artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: StaleBranchList.csv
#           path: ${{ github.workspace }}/StaleBranchList.csv
     
#       - name : Sending notification
#         run: |
#           echo sending notification
          
     
