name: STALE_NOTIFICATION
on:
  workflow_dispatch:
  
jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch details file
        run:  |
          REPO_NAME=${{ github.event.repository.name }}
          echo $REPO_NAME
          git clone https://github.com/2115-27/$REPO_NAME.git
          cd $REPO_NAME/
          
          git branch -a --sort=-committerdate  --format='%(refname:short) |%(authorname)| %(committerdate:short)'>> ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~origin/~~g" ${{ github.workspace }}/BranchDetails.txt
          sed -i "s~,~~g" ${{ github.workspace }}/BranchDetails.txt
          
          echo -----------BranchDetails.txt---------------
          cat ${{ github.workspace }}/BranchDetails.txt
     
      - name: Send notification
        run: |
          sudo apt-get install msmtp
          
          cat  <<EOF >~/.msmtprc
          # Default settings
          defaults
          auth    on
          tls    on
          tls_starttls     on
          tls_trust_file    /etc/ssl/certs/ca-certificates.crt
          logfile ~/.msmtp.log
          # outlook
          account    outlook
          host       outlook.office365.com
          port       587
          from       athulyams2000@outlook.com
          user       athulyams2000@outlook.com
          password   Athulya@2115

          account default : outlook
          EOF
         
          echo ---------pwd,ls and ~/.msmtprc--------------
          pwd
          ls -lrta
          cat ~/.msmtprc
          
          chmod 600 ~/.msmtprc
          ls -lrta
          echo -e "Subject: Regards\n\nSending regards from Terminal." | msmtp -a outlook athulyams2000@outlook.com
          echo test
